name: Keep App Awake

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET Request
        run: |
          curl -sL -A "Mozilla/5.0" "https://eastbourne-wind-niwa-v1-9zdfvwdsj9appa3zkhtkfaf.streamlit.app/" > /dev/null
